# Generated by Django 3.2.6 on 2021-09-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdtname', models.CharField(max_length=50)),
                ('sdtid', models.IntegerField()),
                ('sdtclass', models.CharField(max_length=15)),
                ('sdttel', models.CharField(max_length=30)),
                ('sdtemail', models.EmailField(max_length=254)),
                ('sdtday', models.DateField()),
                ('parentname', models.CharField(max_length=50)),
            ],
        ),
    ]
